dist: trusty
language: ruby
rvm:
 - 2.4.1
before_script:
  - createuser chuks -s -U postgres
  - createdb postit_rails_test --username=chuks
  # - psql -c 'create database postit_rails_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
