POSTGRES_USER: 'andeladeveloper'
POSTGRES_PASSWORD: 'fgsltw@postgres.com'
POSTGRES_HOST: 'localhost'
POSTGRES_DB: 'postit-rails'
POSTGRES_TEST_DB: 'postit-rails-test'
CODECLIMATE_TOKEN: '2f3d33f5b7b2ea228eb00f08733e6ab75161b42c167688ce827ed1a9f537b31e'
